server:
  port: 0 # 8100
  servlet:
    session:
      timeout: 1800 # 세션 기본값 30분

spring:
  application:
    name: auth-api
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 15
    disable-delta: true
    service-url:
      defaultZone: http://admin:admin123@localhost:9000/eureka/

logging:
#  config: classpath:log4j2.xml # 설정안해도 적용됨
  level:
    root: INFO
    '[com.msa]': DEBUG
    '[com.netflix.discovery.DiscoveryClient]': ERROR
#     HikariCP Connection Pool 상태 확인
#    '[com.zaxxer.hikari]': TRACE
#    '[com.zaxxer.hikari.HikariConfig]': DEBUG
#    '[jdbc]': off

# actuator
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, shutdown, gateway
  endpoint:
    health:
      show-details: always

#jasypt:
#  encryptor:
##    bean: jasyptStringEncryptor
#    algorithm: PBEWithMD5AndDES
#    iv-generator-classname: org.jasypt.iv.NoIvGenerator # PBEWithMD5AndDES 사용시 필수 속성







application:
  greeting:
    message: Welcome to the AUTH API
  session:
    key: ENC(XPWx2KKuHOBPZRKDavuJVbTRQH38Wfj7)
  datasource:
    writer:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy # MySQL 설정 : com.mysql.cj.jdbc.Driver
      jdbc-url: ENC(3bME8rV054N+/41JAojejcIgEvYCMpVwXL/dscV1Hk3s7YrPdYsO0oezac95i0ybeW2y8DS4VcB5L9UY1pcWXMhI1KwjODNX4Qu1fATm5abXVVfG3VQTdyE4jaxIANw2M8IKYVgt1RjB0u2XztUAbignUubY8bzQIj8rd6fBEPxkKF9PWzv5bLrP0hrXXJ3fizXUz338XfM=)
      username: ENC(ADWEeKTTBrsTlTVtpH0O/w==)           # DB username
      password: ENC(VEnvoPsejgnDMlEIew2N7biHYqjQiiPa)   # DB password
    reader:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy # MySQL 설정 : com.mysql.cj.jdbc.Driver
      jdbc-url: ENC(3bME8rV054N+/41JAojejcIgEvYCMpVwXL/dscV1Hk3s7YrPdYsO0oezac95i0ybeW2y8DS4VcB5L9UY1pcWXMhI1KwjODNX4Qu1fATm5abXVVfG3VQTdyE4jaxIANw2M8IKYVgt1RjB0u2XztUAbignUubY8bzQIj8rd6fBEPxkKF9PWzv5bLrP0hrXXJ3fizXUz338XfM=)
      username: ENC(ADWEeKTTBrsTlTVtpH0O/w==)           # DB username
      password: ENC(VEnvoPsejgnDMlEIew2N7biHYqjQiiPa)   # DB password