server:
  port: 0 # 8300

spring:
  application:
    name: product-api
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379
# db datasource 설정
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ENC(mYVlmqqLMtdVwPn820H1rjEZaQMLpl1YlhuLnryctNbQtkUljzvRR+sZ22GSg47fjRebDrI7rSuKjQgI1zLPn3Oa5MtVKhRFI0pL6vuke85Ox6B9F1N6FUC1AQFtOLeAAh46JJD+2O4nMbXKb15fXrjJPzUe8NAylgWF+kwI1Y8=)
      username: ENC(ADWEeKTTBrsTlTVtpH0O/w==)
      password: ENC(VEnvoPsejgnDMlEIew2N7biHYqjQiiPa)

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    disable-delta: true
    service-url:
      defaultZone: http://admin:admin123@localhost:9000/eureka/

greeting:
  message: Welcome to the Product API

logging:
  level:
    com.msa: DEBUG