server:
  port: 0 # 8200
  servlet:
    session:
      timeout: 1800 # 세션 기본값 30분

spring:
  application:
    name: system-api
  session:
    store-type: redis
  redis:
    host: localhost
    port: 6379

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    registry-fetch-interval-seconds: 15
    disable-delta: true
    service-url:
      defaultZone: http://admin:admin123@localhost:9000/eureka/

logging:
  level:
    root: INFO
    '[com.msa]': DEBUG

#jasypt:
#  encryptor:
##    bean: jasyptStringEncryptor
#    algorithm: PBEWithMD5AndDES
#    iv-generator-classname: org.jasypt.iv.NoIvGenerator # PBEWithMD5AndDES 사용시 필수 속성







application:
  greeting:
    message: Welcome to the System API
  session:
    key: ENC(XPWx2KKuHOBPZRKDavuJVbTRQH38Wfj7)
  datasource:
    writer:
      driver-class-name: com.mysql.cj.jdbc.Driver # MySQL 설정 : com.mysql.cj.jdbc.Driver | JDBC LOG 설정 : net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: ENC(5FyapLWk4uuCj5zASq0NwmuoyRXp6mXKdwt9PF9QmMM2S6U7sWHQ4BvpFIsXBgl9E5ejvRTJxCcWWOARFi+Zj2iqM9pTGvZpxeALi63VaRh9g3pUS6nodaV+jwVcU9e+yJEyuoVZjOJaMoRoWvi0tnMxWQab5PBAn9w79USi/S2GxgGbmskk1auZVyXCTSjF)
      username: ENC(ADWEeKTTBrsTlTVtpH0O/w==)           # DB username
      password: ENC(VEnvoPsejgnDMlEIew2N7biHYqjQiiPa)   # DB password
    reader:
      driver-class-name: com.mysql.cj.jdbc.Driver # MySQL 설정 : com.mysql.cj.jdbc.Driver | JDBC LOG 설정 : net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: ENC(5FyapLWk4uuCj5zASq0NwmuoyRXp6mXKdwt9PF9QmMM2S6U7sWHQ4BvpFIsXBgl9E5ejvRTJxCcWWOARFi+Zj2iqM9pTGvZpxeALi63VaRh9g3pUS6nodaV+jwVcU9e+yJEyuoVZjOJaMoRoWvi0tnMxWQab5PBAn9w79USi/S2GxgGbmskk1auZVyXCTSjF)
      username: ENC(ADWEeKTTBrsTlTVtpH0O/w==)           # DB username
      password: ENC(VEnvoPsejgnDMlEIew2N7biHYqjQiiPa)   # DB password